apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: victoria-metrics

resources:
  - ../../base/victoria-metrics-cluster
  - ../../base/victoria-metrics-agent
  - ../../base/grafana

patchesStrategicMerge:
  - patches/patch-cluster-values.yaml
  - patches/patch-agent-values.yaml
  - patches/patch-grafana-values.yaml