apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: victoria-metrics-cluster
valuesInline: 
  vmselect:
    replicaCount: 1
    podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8481"

  vminsert:
    replicaCount: 1
    podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8480"
        
  vmstorage:
    replicaCount: 1
    persistentVolume:
      storageClass: longhorn
    podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8482"